CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT NUMERIC(38), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
CREATE TABLE PERMISSION (ID_PERMISSION BIGINT NOT NULL, AGREGAR BOOLEAN, BORRAR BOOLEAN, EDITAR BOOLEAN, PERMISO varchar(200), VER BOOLEAN, PRIMARY KEY (ID_PERMISSION));
CREATE TABLE PRINCIPAL (ID_PRINCIPAL BIGINT NOT NULL, ACTIVO VARCHAR(200), ROL VARCHAR(200), PRIMARY KEY (ID_PRINCIPAL));
CREATE TABLE USUARIO (ID_USUARIO BIGINT NOT NULL, ACTIVO VARCHAR(200), EMAIL VARCHAR(200), NAME VARCHAR(200), PASSWORD VARCHAR(200), PRINCIPAL_ID_PRINCIPAL BIGINT, PRIMARY KEY (ID_USUARIO));
CREATE TABLE PRINCIPAL_PERMISSION (Principal_ID_PRINCIPAL BIGINT NOT NULL, permissions_ID_PERMISSION BIGINT NOT NULL, PRIMARY KEY (Principal_ID_PRINCIPAL, permissions_ID_PERMISSION));
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_PRINCIPAL_ID_PRINCIPAL FOREIGN KEY (PRINCIPAL_ID_PRINCIPAL) REFERENCES PRINCIPAL (ID_PRINCIPAL);
ALTER TABLE PRINCIPAL_PERMISSION ADD CONSTRAINT FK_PRINCIPAL_PERMISSION_permissions_ID_PERMISSION FOREIGN KEY (permissions_ID_PERMISSION) REFERENCES PERMISSION (ID_PERMISSION);
ALTER TABLE PRINCIPAL_PERMISSION ADD CONSTRAINT FK_PRINCIPAL_PERMISSION_Principal_ID_PRINCIPAL FOREIGN KEY (Principal_ID_PRINCIPAL) REFERENCES PRINCIPAL (ID_PRINCIPAL);
